name: lint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install poetry
        run: pipx install poetry
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: "poetry"
      - name: install dependencies.
        run: poetry install
      - name: run pylint
        run: poetry run pylint ./src
